# Generated by Django 5.2.7 on 2025-10-16 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('employment_status', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('household_size', models.PositiveIntegerField()),
                ('has_children', models.BooleanField(default=False)),
                ('monthly_income_sgd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preferred_category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_category', models.CharField(max_length=50)),
                ('product_subcategory', models.CharField(max_length=50)),
                ('quantity_on_hand', models.PositiveIntegerField()),
                ('reorder_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
        ),
    ]
